services:
  db:
    image: postgres:15
    container_name: autoescola_db
    environment:
      POSTGRES_DB: autoescola_db
      POSTGRES_USER: autoescola
      POSTGRES_PASSWORD: autoescola
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: autoescola_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pg.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
volumes:
  pgdata:
